services:
  # PostgreSQL database service
  postgres:
    image: postgres:15

    # Environment variables for PostgreSQL initialization
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library

    # Mount volumes for data persistence and configuration
    volumes:
      - pgdata:/var/lib/postgresql/data

    # Allows connections to localhost:5432 from your machine
    ports:
      - '5433:5432'

    # Allows other services to communicate with postgres by service name
    networks:
      - library-network

    # Health check to verify PostgreSQL is ready to accept connections
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"
      - "./definitions.json:/etc/rabbitmq/definitions.json:ro"
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
    # ports:
    #   - '8000:8000'
    networks:
      - library-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    env_file:
      - notification-service/.env.docker
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - library-network

  # grpc-server:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   command: ["uv", "run", "python", "-m", "app.grpc_server"]
  #   env_file:
  #     - backend/.env.docker
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1.0'
  #   ports:
  #     - '50052:50052'
  #     - '9000:9000'
  #   networks:
  #     - library-network

  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - '9090:9090'
  #   depends_on:
  #     - backend
  #     - grpc-server
  #   networks:
  #     - library-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env.docker
    depends_on:
      - backend
    ports:
      - '3000:3000'
    networks:
      - library-network

# Define named volumes for persistent data storage
volumes:
  pgdata:

# Define custom networks for service communication
networks:
  library-network:
    # To allow containers to communicate with each other
    # within the network and isolate from other containers
    external: true
