global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'library-rest'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'library-grpc'
    static_configs:
      - targets: ['grpc-server:9000']
      